source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

# Comment out this line if working on cineio-ios
#pod 'cineio-broadcast-ios', '~> 0.7'

# Uncomment this line if working on cineio-ios
pod 'cineio-broadcast-ios', path: '/Users/soplwang/Projects/JRs.tv/jrstv-broadcast-ios'

# Uncomment this line if working on VideoCore
pod 'VideoCore', path: '/Users/soplwang/Projects/JRs.tv/VideoCore'
