platform :ios, '7.0'

# Comment out this line if working on cineio-ios
pod 'cineio-ios', '~> 0.5'

# Uncomment this line if working on cineio-ios
#pod 'cineio-ios', path: '/Users/jeffrey/dev/cine-dev/cineio-ios'

# Uncomment this line if working on VideoCore
#pod 'VideoCore', path: '/Users/jeffrey/dev/cine-dev/VideoCore'
