platform :ios, '6.0'

pod 'cineio-ios', '~> 0.1.3'
#pod 'cineio-ios', path: '/Users/jeffrey/dev/cine-dev/cineio-ios'

pod 'VideoCore', git: 'https://github.com/cine-io/VideoCore.git', branch: 'fix-cocoapod-namespace-collision'
#pod 'VideoCore', '~> 0.1.1'
