platform :ios, '6.0'

pod 'cineio-ios', '~> 0.1.3'

#pod 'VideoCore', '~> 0.1.3'
# until this bug is fixed, use git: https://github.com/jamesghurley/VideoCore/issues/20
pod 'VideoCore', git: 'https://github.com/jamesghurley/VideoCore.git'

pod 'Masonry', '~> 0.5.2'
